[package]
name = "rust-thread-comparative"
version = "0.1.0"
authors = ["xavi <xavi@ondono.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "*"
rayon = "*"
